baseURL = "https://github.com/Lis-Ma/raum-fuer-worte-konstanz/"
languageCode = "de-de"
title = "Raum für Worte"

relativeURLs = true
canonifyURLs = false

[params]
  subtitle = "Reden, die bewegen – über Identität, Mutterschaft und Leben"
  accent = "#c9a66b"
  bg = "#fefaf2"
